export const FilmUrls: any[] = [
  'Spirited Away',
  'My Neighbor Totoro',
  'Laputa Castle in the Sky',
  'Princess Mononoke',
  'Nausicaa of the Valley of the Wind',
  'Arrietty',
  'Grave of the Fireflies',
  "Howl's Moving Castle",
  "Kiki's Delivery Service",
  'My Neighbors the Yamadas',
  'Ocean Waves',
  'Only Yesterday',
  'Pom Poko',
  'Ponyo',
  'Porco Rosso',
  'Tales From Earthsea',
  'From Up On Poppy Hill',
  'The Cat Returns',
  'The Tale of Princess Kaguya',
  'The Wind Rises',
  'When Marnie Was There',
  'Whisper of the Heart',
];
